-- ============================================================================
-- Full import: real Strauss inventory data, including photos, supplier,
-- cost, and reorder links. Run 008_item_metadata.sql BEFORE this file.
-- Run this ONCE, after creating the 'Strauss' property in the app.
-- ============================================================================

-- Step 1: create storage locations under Strauss (skips any that already exist)
insert into public.locations (property_id, name)
select (select id from public.properties where name = 'Strauss' limit 1), loc
from (values
  ('Basement Bath'),
  ('Bath drawer'),
  ('Bath vanity'),
  ('Beverage bin'),
  ('Beverage drawer'),
  ('Beverage fridge'),
  ('Freezer'),
  ('Kitchen cabinet'),
  ('Kitchen drawer'),
  ('Kitchen pantry'),
  ('Laundry Room'),
  ('Office / Supply'),
  ('Produce bin'),
  ('Refrigerator'),
  ('Shower niche'),
  ('Supply cabinet')
) as t(loc)
where not exists (
  select 1 from public.locations l
  where l.property_id = (select id from public.properties where name = 'Strauss' limit 1)
    and l.name = t.loc
);

-- Step 2: create inventory items with full metadata
-- Quantities start at 0 (par levels are out of scope per prior decision) --
-- adjust real on-hand counts afterward in the app.
-- NOTE: photo_url values here are Google Drive 'view' links, not direct
-- image URLs — they will NOT render as inline <img> thumbnails as-is.
-- They're stored so the links aren't lost; converting them to direct-
-- viewable image URLs is a separate follow-up if you want real photo
-- previews in the app.
insert into public.inventory_items
  (property_id, location_id, name, category, current_qty, min_qty, unit, supplier, unit_cost, reorder_link, photo_url)
select
  (select id from public.properties where name = 'Strauss' limit 1),
  (select id from public.locations where property_id = (select id from public.properties where name = 'Strauss' limit 1) and name = t.loc),
  t.item_name, t.category, 0, 0, 'pcs',
  nullif(t.supplier, ''),
  nullif(t.unit_cost, '')::numeric,
  nullif(t.reorder_link, ''),
  nullif(t.photo_url, '')
from (values
  ('Bobby Pins (assorted)', 'Hair Accessories', 'Bath drawer', 'Amazon', '', '', ''),
  ('Hair Elastics / Ties', 'Hair Accessories', 'Bath drawer', 'Amazon', '', '', ''),
  ('Pantene Pro-V Daily Moisture Renewal Conditioner (travel)', 'Hair Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Saltair Santal Bloom Conditioner (pump)', 'Shower Dispenser', 'Shower niche', 'Amazon', '', '', ''),
  ('Saltair Santal Bloom Hydrating Shampoo (pump)', 'Shower Dispenser', 'Shower niche', 'Amazon', '', '', ''),
  ('Wet Brush Original Detangler', 'Accessory (durable)', 'Bath drawer', 'Amazon', '', '', ''),
  ('Aquaphor Healing Ointment Advanced Therapy (travel tube)', 'Skin / First Aid', 'Bath vanity', 'Amazon', '', '', ''),
  ('BIC Silky Touch Women''s Disposable Razors', 'Shaving', 'Bath drawer', 'Amazon', '', '', ''),
  ('Dove Antiperspirant Deodorant (travel)', 'Body Care', 'Bath drawer', 'Amazon', '', '', ''),
  ('Dove Deep Moisture Body Wash (travel)', 'Body Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Dove Men+Care Clean Comfort Dry Spray Antiperspirant', 'Body Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Neutrogena Makeup Remover Cleansing Towelettes', 'Skin Care', 'Bath drawer', 'Amazon', '', '', ''),
  ('Purell Advanced Hand Sanitizer (travel)', 'Hand Sanitizer', 'Bath drawer', 'Amazon', '', '', ''),
  ('Saltair Santal Bloom Body Wash (pump)', 'Shower Dispenser', 'Shower niche', 'Amazon', '', '', ''),
  ('Crest Scope Classic Mouthwash (travel)', 'Oral Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Dental Flossers (individually wrapped)', 'Oral Care', 'Bath drawer', 'Amazon', '', '', ''),
  ('Disposable Toothbrush + Toothpaste Kit (individually wrapped)', 'Oral Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Listerine Cool Mint PocketPaks Breath Strips (24 ct)', 'Oral Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Advil Ibuprofen 200 mg Tablets (travel vial)', 'OTC Medicine', 'Bath vanity', 'Amazon', '', '', ''),
  ('Contact Lens Case', 'Eye / Lens Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Opti-Free Replenish Disinfecting Solution', 'Eye / Lens Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('TUMS Smoothies Extra Strength 750 Assorted Fruit (12 ct)', 'OTC Medicine', 'Bath vanity', 'Amazon', '', '', ''),
  ('Tylenol Extra Strength Rapid Release Gels 500 mg (24 ct)', 'OTC Medicine', 'Bath vanity', 'Amazon', '', '', ''),
  ('Cotton Balls / Rounds', 'Cotton & Swabs', 'Bath drawer', 'Amazon', '', '', ''),
  ('Cotton Swabs / Q-tips', 'Cotton & Swabs', 'Bath drawer', 'Amazon', '', '', ''),
  ('Eishes Chayil Bedika Cloths (48 ct)', 'Personal / Ritual', 'Bath vanity', 'Amazon', '', '', ''),
  ('Pads (Always Radiant)', 'Feminine Care', 'Bath drawer', 'Amazon', '', '', ''),
  ('Tampons (Tampax Radiant)', 'Feminine Care', 'Bath drawer', 'Amazon', '', '', ''),
  ('Facial Tissues (Kleenex)', 'Paper Goods', 'Bath vanity', 'Amazon', '', '', ''),
  ('Senteurs d''Orient Fleurs d''Oasis Hand Cream (La Creme)', 'Hand Care', 'Bath vanity', 'Amazon', '', '', ''),
  ('Senteurs d''Orient Fleurs d''Oasis Hand Wash (Le Lavabo)', 'Hand Soap', 'Bath vanity', 'Amazon', '', '', ''),
  ('Nescafe Tasters Choice Decaf Instant Coffee Sticks', 'Coffee', 'Beverage drawer', 'Amazon', '10.48', '', ''),
  ('Nescafe Tasters Choice House Blend Instant Coffee Sticks', 'Coffee', 'Beverage drawer', 'Kosher West', '', '', ''),
  ('Twinings Peppermint Herbal Tea', 'Tea', 'Beverage drawer', 'Costco', '', '', ''),
  ('Domino Sugar Packets', 'Sweetener', 'Beverage drawer', 'Costco', '', '', ''),
  ('Equal (Sweetener)', 'Sweetener', 'Beverage drawer', 'Costco', '', '', ''),
  ('Raw / Turbinado Sugar Packets', 'Sweetener', 'Beverage drawer', 'Costco', '', '', ''),
  ('Splenda (No-Calorie Sweetener)', 'Sweetener', 'Beverage drawer', 'Costco', '', '', ''),
  ('Crystal Light Lemonade Drink Mix (packets)', 'Drink Mix', 'Beverage drawer', 'Costco', '', '', ''),
  ('Poland Spring Bottled Water (0.5 L)', 'Bottled Water', 'Beverage fridge', 'BJ''s Wholesale', '', '', ''),
  ('Polar Seltzer Black Cherry', 'Canned Beverage', 'Beverage fridge', 'Costco', '', '', ''),
  ('Polar Seltzer Lemon', 'Canned Beverage', 'Beverage fridge', 'Costco', '', '', ''),
  ('Polar Seltzer Lime', 'Canned Beverage', 'Beverage fridge', 'Costco', '', '', ''),
  ('Polar Seltzer Original (Regular)', 'Canned Beverage', 'Beverage fridge', 'Costco', '', '', ''),
  ('Polar Seltzer Raspberry Lime', 'Canned Beverage', 'Beverage fridge', 'Costco', '', '', ''),
  ('Dixie Hot Cups + Lids', 'Disposables', 'Beverage drawer', 'Costco', '', '', ''),
  ('Iced Coffee / Smoothie Cups + Lids', 'Disposables', 'Beverage drawer', 'Costco', '', '', ''),
  ('Plastic Coffee Stirrers', 'Disposables', 'Beverage drawer', 'Costco', '', '', ''),
  ('Plastic Forks', 'Disposables', 'Beverage drawer', 'Costco', '', '', ''),
  ('Plastic Spoons', 'Disposables', 'Beverage drawer', 'Costco', '', '', ''),
  ('Poland Spring Bottled Water (0.5 L)', 'Bottled Water', 'Supply cabinet', 'BJ''s Wholesale', '', '', ''),
  ('COREtec The Original ENCORE LVT Floor Cleaner (1 gal)', 'Cleaning Supplies', 'Supply cabinet', 'Costco', '', '', ''),
  ('Facial Tissues (Kleenex)', 'Paper Goods', 'Supply cabinet', 'Costco', '', '', ''),
  ('Purell Advanced Hand Sanitizer (single-use packets 125 ct)', 'Cleaning', 'Supply cabinet', 'Costco', '', '', ''),
  ('Lysol All-Purpose Cleaner Lemon Breeze', 'All-Purpose', 'Basement Bath', 'Costco', '', '', ''),
  ('Lysol Power Clinging Gel Toilet Bowl Cleaner', 'Toilet Care', 'Basement Bath', 'Costco', '', '', ''),
  ('Murphy Oil Soap Wood Cleaner (concentrated)', 'Wood / Floor Care', 'Basement Bath', 'Costco', '', '', ''),
  ('Lysol Power Clean 2X Multi-Surface Cleaner', 'Multi-Surface', 'Basement Bath', 'Costco', '', '', ''),
  ('Owell Nitrile Gloves Black Powder-Free (M 100)', 'PPE / Gloves', 'Basement Bath', 'Amazon', '', '', ''),
  ('Resolve Stain Remover Carpet Cleaner (PRO)', 'Carpet / Upholstery', 'Basement Bath', 'Costco', '', '', ''),
  ('Clorox Plus Tilex Daily Shower Cleaner', 'Shower Care', 'Basement Bath', 'Costco', '', '', ''),
  ('Windex Glass & More Multi-Surface Spray', 'Glass Care', 'Basement Bath', 'Costco', '', '', ''),
  ('Windex Commercial Line Original Refill', 'Glass Care - Refill', 'Basement Bath', 'Costco', '', '', ''),
  ('Soft Scrub All-Purpose Cleanser Lemon', 'Abrasive / All-Purpose', 'Basement Bath', 'Costco', '', '', ''),
  ('Mr. Clean Magic Eraser Original (6 pk)', 'Scrub Pads', 'Basement Bath', 'Costco', '', '', ''),
  ('Avery 94219 Durable White Film Labels (1.5x1 32/sheet)', 'Label Stock', 'Office / Supply', 'Amazon', '', '', ''),
  ('Dreft Stage 1: Newborn Liquid Detergent (32 loads)', 'Baby Detergent', 'Laundry Room', 'Costco', '', '', ''),
  ('Mama Bear Gentle Baby Wipes Fragrance-Free', 'Baby Wipes', 'Laundry Room', 'Amazon', '', '', ''),
  ('OxiClean Max Force Laundry Stain Remover', 'Stain Remover', 'Laundry Room', 'Costco', '', '', ''),
  ('Shout Triple Acting Laundry Stain Remover', 'Stain Remover', 'Laundry Room', 'Costco', '', '', ''),
  ('Downy Wrinkle Releaser + Crisp Linen Fabric Spray', 'Fabric Care', 'Laundry Room', 'Costco', '', '', ''),
  ('Heinz Tomato Ketchup', 'Condiment', 'Kitchen pantry', 'Amazon', '2.48', 'https://www.target.com/p/heinz-tomato-ketchup-14oz/-/A-13018449', 'https://drive.google.com/file/d/1OAxYEcZ5wamVBEt6qLnXJ7mEc3b1R37P/view'),
  ('Sweet Baby Ray''s Barbecue Sauce', 'BBQ Sauce', 'Kitchen pantry', 'Amazon', '3.14', 'https://www.walmart.com/ip/Sweet-Baby-Ray-s-Original-Barbecue-Sauce-40-oz/10450530', 'https://drive.google.com/file/d/1JzYCtG6hfFfRjOoNzob5JAOLbHXvYh3C/view'),
  ('Frank''s RedHot Original Hot Sauce', 'Hot Sauce', 'Kitchen pantry', 'Amazon', '3.48', 'https://www.walmart.com/ip/Frank-s-RedHot-Original-Cayenne-Pepper-Sauce-12-fl-oz/10313175', 'https://drive.google.com/file/d/1OvfTxuK6EtXbl93i10cYdqO9JqDh_6Ln/view'),
  ('Grey Poupon Dijon Mustard', 'Mustard', 'Kitchen pantry', 'Amazon', '3.88', 'https://www.walmart.com/ip/Grey-Poupon-Dijon-Mustard-with-White-Wine-8-oz-Jar/10292025', 'https://drive.google.com/file/d/1cr3Tdt6O91QEu_jbz3t3KMUMr_5n_uDW/view'),
  ('Gold''s Duck Sauce', 'Condiment', 'Kitchen pantry', 'Amazon', '2.50', 'https://kosherwest.com', 'https://drive.google.com/file/d/1IdR3kGm88wrh0r61GmbAGdCwj0zQn96i/view'),
  ('Lieber''s Sriracha', 'Hot Sauce', 'Kitchen pantry', 'Amazon', '4.99', 'https://kosherwest.com', 'https://drive.google.com/file/d/1x8SDJNG99X7cj0LIFVhL2Eiv5kHtBo-v/view'),
  ('Tuscanini Balsamic Glaze', 'Vinegar Glaze', 'Kitchen pantry', 'Amazon', '7.50', 'https://kosherwest.com', 'https://drive.google.com/file/d/1UbBF11euyrGR185mygmNReYnxp9iMOxK/view'),
  ('Kedem White Wine Vinegar', 'Vinegar', 'Kitchen pantry', 'Kosher West', '3.99', 'https://kosherwest.com', 'https://drive.google.com/file/d/1590JDyGBC3ItspXRPIUSMBHxyHwxqWnr/view'),
  ('Achva Sesame Tahini', 'Spread', 'Kitchen pantry', 'Amazon', '6.50', 'https://kosherwest.com', 'https://drive.google.com/file/d/1p8XhwgAdFALlIQzrBbYLSsyCzQawPdka/view'),
  ('Haolam Grated Parmesan Cheese', 'Cheese', 'Kitchen pantry', 'Kosher West', '4.50', 'https://kosherwest.com', 'https://drive.google.com/file/d/1vt0m2E9RVl4a_g1QkJNklC6Fjugv86FU/view'),
  ('Dagim Chunk Light Tuna in Water', 'Canned Fish', 'Kitchen pantry', 'Kosher West', '2.25', 'https://kosherwest.com', 'https://drive.google.com/file/d/1gzZQbDK38tGShJ18YD_JW-5aA-OlzwIz/view'),
  ('Tuscanini Tomato Paste', 'Canned', 'Kitchen pantry', 'Amazon', '1.99', 'https://kosherwest.com', 'https://drive.google.com/file/d/1LTg4PmBPizZ9lHQIuWDorNMNQY_kE8Jd/view'),
  ('Gefen Cucumbers in Brine (Pickles)', 'Pickles', 'Kitchen pantry', 'Kosher West', '3.50', 'https://kosherwest.com', 'https://drive.google.com/file/d/1QlnccE8FV3tF6Ug6yciNuNeYoRPY51RS/view'),
  ('Onions (Tri-Color)', 'Produce', 'Produce bin', 'Kosher West', '2.00', '', 'https://drive.google.com/file/d/1TBGOEKHTpALZfXo54a8NjQZCND-hqy8c/view'),
  ('Argo Corn Starch', 'Baking', 'Kitchen pantry', 'Amazon', '1.88', 'https://www.walmart.com/ip/Argo-Gloss-Starch-16-oz/10292358', 'https://drive.google.com/file/d/19-mgWf3snt5zPrvaidw-ktwgIG9V0yCq/view'),
  ('Kellogg''s Corn Flake Crumbs', 'Coating', 'Kitchen pantry', 'Amazon', '3.58', 'https://www.target.com/p/kellogg-39-s-corn-flakes-crumbs-21oz/-/A-13350170', 'https://drive.google.com/file/d/1EocYP3ICgSavhCtGLiWyE4fa2JzHMHzk/view'),
  ('Ronzoni Elbows (Macaroni)', 'Pasta', 'Kitchen pantry', 'Amazon', '1.69', 'https://www.target.com/p/ronzoni-elbows-pasta-16oz/-/A-13155726', 'https://drive.google.com/file/d/14iH6Ir155RRWUqVbmHKW3UZugVkD8Zkz/view'),
  ('Haddar Italian Dressing & Seasoning Mix', 'Dressing Mix', 'Kitchen pantry', 'Kosher West', '1.99', 'https://kosherwest.com', 'https://drive.google.com/file/d/1vvkqySoM4gM5RhPELKFVYwqhUaiRNCKt/view'),
  ('Ortega Grande Taco Kit', 'Meal Kit', 'Kitchen pantry', 'Amazon', '3.50', 'https://kosherwest.com', 'https://drive.google.com/file/d/1Jx_fReo8ZcLm0gP_1m3KGAQYrQZ5jrvk/view'),
  ('Pas Yisroel Whole Wheat Pita 6 Pk', 'Bread', 'Kitchen pantry', 'Kosher West', '3.99', '', ''),
  ('Plastico Plates 7 in', 'Disposable', 'Kitchen pantry', 'Kosher West', '2.99', '', ''),
  ('Dole Carrots Cello California 16 Oz', 'Produce', 'Produce bin', 'Kosher West', '1.19', '', ''),
  ('Gefen Cholent Mix Chulent 16 Oz', 'Spice Mix', 'Kitchen pantry', 'Kosher West', '2.29', '', ''),
  ('Bean Broccoli Florets 24 Oz', 'Frozen Vegetables', 'Freezer', 'Kosher West', '3.49', '', ''),
  ('Poskesz Rice Cake Minis Plain Box 4 Oz', 'Crackers', 'Kitchen pantry', 'Kosher West', '3.49', '', ''),
  ('Scallions Bunch', 'Produce', 'Produce bin', 'Kosher West', '0.79', 'https://kosherwest.com/Lakewood-NJ/category/4891', ''),
  ('Verdini Fresh Dill', 'Herbs Fresh', 'Produce bin', 'Kosher West', '1.99', '', ''),
  ('Haolam Fancy Mozzarella & Cheese (Sliced)', 'Cheese', 'Refrigerator', 'Kosher West', '5.99', '', ''),
  ('Pride Of The Farm Fancy Sliced Cheese 16 Oz', 'Cheese', 'Refrigerator', 'Kosher West', '4.99', '', ''),
  ('Soy Cheese Deli Smoked Slices', 'Cheese Alternative', 'Refrigerator', 'Kosher West', '6.99', '', ''),
  ('Pas Slimmer''s Wheat Wraps Low Carb', 'Bread', 'Kitchen pantry', 'Kosher West', '3.99', '', ''),
  ('Jelly Rings', 'Candy', 'Kitchen pantry', 'Kosher West', '4.99', '', ''),
  ('Poskesz Rolled Wafers Chocolate', 'Cookie', 'Kitchen pantry', 'Kosher West', '1.79', '', ''),
  ('Pas Mezonos Hot Dog Buns', 'Bread', 'Kitchen pantry', 'Kosher West', '5.29', '', ''),
  ('Gefen Onion Powder Deluxe 8 oz', 'Spice', 'Kitchen pantry', 'Kosher West', '6.99', '', ''),
  ('Smart Balance Dairy Free Butter', 'Butter Alternative', 'Refrigerator', 'Kosher West', '6.49', '', ''),
  ('Pretzilla Mini Pretzel Buns 6 Pk', 'Bread', 'Kitchen pantry', 'Kosher West', '7.49', '', ''),
  ('Haddar 40 Ct Family Pack Matzo', 'Matzo', 'Kitchen pantry', 'Kosher West', '7.49', '', ''),
  ('Navel Pastrami', 'Meat Deli', 'Refrigerator', 'Kosher West', '29.99', '', ''),
  ('Osem Consomme (Chicken) Soup Mix', 'Soup Mix', 'Kitchen pantry', 'Kosher West', '7.99', '', ''),
  ('Schwartz Appetizing Spicy Smoked Beef', 'Meat Deli', 'Refrigerator', 'Kosher West', '6.99', '', ''),
  ('Babka Amareto Ring', 'Dessert', 'Kitchen pantry', 'Kosher West', '14.99', '', ''),
  ('Kedem Grape Juice 22 Oz', 'Beverage', 'Beverage bin', 'Kosher West', '3.99', '', ''),
  ('Tomatoes Grape', 'Produce', 'Produce bin', 'Kosher West', '2.99', 'https://kosherwest.com/Lakewood-NJ/category/4889', ''),
  ('Side Of Salmon', 'Fish', 'Freezer', 'Kosher West', '11.99', '', ''),
  ('Milk Munch Chocolate Bar', 'Candy', 'Kitchen pantry', 'Kosher West', '1.50', '', ''),
  ('Gushers Variety Pack', 'Candy', 'Kitchen pantry', 'Kosher West', '4.99', '', ''),
  ('Haolam Light Cream Cheese', 'Cheese', 'Refrigerator', 'Kosher West', '3.99', '', ''),
  ('Stella Doro Swiss Fudge Cookies 8 Oz', 'Cookie', 'Kitchen pantry', 'Kosher West', '4.99', '', ''),
  ('Meal Mart Kishka 16 Oz', 'Meat', 'Kitchen pantry', 'Kosher West', '5.99', '', ''),
  ('Jet Foil 5Lb Pans With Lid 4 Ct', 'Disposable', 'Kitchen pantry', 'Kosher West', '4.49', '', ''),
  ('Ground Beef 1 Lb', 'Meat', 'Refrigerator', 'Kosher West', '8.99', '', ''),
  ('Dill Pickles Purple Cabbage 16 Oz', 'Pickles', 'Kitchen pantry', 'Kosher West', '3.99', '', ''),
  ('Corn Poppin Pizza Cheese & Snack', 'Snack', 'Kitchen pantry', 'Kosher West', '4.99', '', ''),
  ('Yellow Onion 5lb Bag', 'Produce', 'Produce bin', 'Kosher West', '3.99', '', ''),
  ('Babka Iced Cinnamon Buns', 'Bread Dessert', 'Kitchen pantry', 'Kosher West', '9.99', '', ''),
  ('Flanken Roast', 'Meat', 'Freezer', 'Kosher West', '34.99', '', ''),
  ('Elite Must Spearmint Gum', 'Candy', 'Kitchen pantry', 'Kosher West', '3.49', '', ''),
  ('Lieber''s Chick Peas 15 Oz', 'Legumes Canned', 'Kitchen pantry', 'Kosher West', '1.89', '', ''),
  ('Norman''s Lowfat Vanilla Yogurt', 'Dairy', 'Refrigerator', 'Kosher West', '2.50', '', ''),
  ('Drizzilicious Cinnamon Swirl', 'Snack', 'Kitchen pantry', 'Kosher West', '9.49', '', ''),
  ('Peeled Garlic 1 Lb', 'Produce Prepared', 'Refrigerator', 'Kosher West', '6.99', '', ''),
  ('Liebers Mini Snackers Family Pack', 'Candy', 'Kitchen pantry', 'Kosher West', '5.99', '', ''),
  ('Klein''s Natural Granola 12 Oz', 'Cereal', 'Kitchen pantry', 'Kosher West', '5.75', '', ''),
  ('Byun Crushed Garlic Cubes 2.8 oz', 'Condiment', 'Kitchen pantry', 'Kosher West', '4.49', '', ''),
  ('Rib Steak Family Pack', 'Meat', 'Freezer', 'Kosher West', '14.49', '', ''),
  ('The Kosher Cook Kitchen Knife', 'Tool Utensil', 'Kitchen drawer', 'Kosher West', '7.99', '', ''),
  ('Lieber''s Peanut Butter Pretzels', 'Snack', 'Kitchen pantry', 'Kosher West', '0.69', '', ''),
  ('Made Good Chocolate Chip Cookies', 'Cookie Snack', 'Kitchen pantry', 'Kosher West', '5.49', '', ''),
  ('Ortega Fajita Seasoning Kit 1 Oz', 'Spice Mix', 'Kitchen pantry', 'Kosher West', '1.49', '', ''),
  ('Ortega Taco Seasoning Mix', 'Spice Mix', 'Kitchen pantry', 'Kosher West', '1.49', '', ''),
  ('Poskesz Encores Bites Unwrapped', 'Snack Candy', 'Kitchen pantry', 'Kosher West', '3.99', '', ''),
  ('Alprose Napolitains Mix', 'Chocolate Candy', 'Kitchen pantry', 'Kosher West', '8.99', '', ''),
  ('Cauliflower Blossom', 'Produce Fresh', 'Produce bin', 'Kosher West', '8.99', '', ''),
  ('Hanover Sugar Snap Peas 12 Oz', 'Frozen Vegetables', 'Freezer', 'Kosher West', '3.99', '', ''),
  ('Stemless Wine Tasters 4 Oz 8 Ct', 'Glassware', 'Kitchen cabinet', 'Kosher West', '4.99', '', ''),
  ('Sizgit Hoola Hoops Flavored Onion Rings', 'Snack Chips', 'Kitchen pantry', 'Kosher West', '0.89', '', ''),
  ('Sizgit Onion Garlic Wheelz 0.5 Oz', 'Snack Chips', 'Kitchen pantry', 'Kosher West', '0.89', '', ''),
  ('Sunny Kits Rosemary', 'Herb Fresh', 'Produce bin', 'Kosher West', '1.99', '', ''),
  ('Beef Bones Soup Bones', 'Meat', 'Freezer', 'Kosher West', '6.99', '', ''),
  ('Osem Seasoned Beef Instant Boillon', 'Seasoning Broth', 'Kitchen pantry', 'Kosher West', '2.99', '', ''),
  ('Gefen Onion Rings Frozen Fresh Made', 'Frozen Vegetables', 'Freezer', 'Kosher West', '3.99', '', ''),
  ('Smart Balance Peanut Butter Creamy', 'Spread', 'Kitchen pantry', 'Kosher West', '4.99', '', '')
) as t(item_name, category, loc, supplier, unit_cost, reorder_link, photo_url);