-- 126_help_articles_content_reconciliation.sql
-- RECONCILIATION -- this content is ALREADY LIVE. Captures help_articles
-- content for the two categories completed so far (Staff & Permissions 28,
-- Troubleshooting 16 = 44 rows), which were written to production by direct
-- SQL and never entered migration history.
--
-- Written as an idempotent UPSERT, not UPDATE-by-id, and this is deliberate:
-- 122_help_articles.sql creates the table but seeds ZERO rows, so the base
-- English content was never in migration history either. An UPDATE-only
-- reconciliation would silently affect 0 rows on a fresh environment and
-- would NOT meet the stated goal of "a fresh environment reproduces them."
-- This file carries the full row (EN + ES + keywords) so it actually does.
--
-- STILL OUTSTANDING (pre-existing gap, wider than today's changes): the
-- other 56 help_articles rows -- Getting Started 10, Inventory 9, Jewish
-- Calendar 14, Multi-Property 6, Recipes & Meals 10, Shopping 7 -- are also
-- absent from migration history and have no Spanish yet. They need the same
-- treatment as their translations land.
--
-- Generated programmatically from the live rows, not transcribed by hand:
-- these are staff-facing instructions in a language that cannot be eyeballed
-- for silent typos here, so machine generation + a hash check was the only
-- honest path.
--
-- FAQ-040's English correction is included in the values below: it had
-- directed staff to "My Day > Tasks > Household Instructions", a page that
-- has never existed. StaffOnboardingModal (messages/en.json:384) already
-- said the correct thing ("Check Shift Handover").

insert into help_articles
  (id, category, question, short_answer, detailed_answer, question_es, short_answer_es, detailed_answer_es, keywords)
values
  ('FAQ-005', 'Staff & Permissions', 'Does everyone in the household need access?', 'No. Access depends on individual roles and necessity.', 'No. Access depends on the person''s role. Roles include Homeowner, Manager, and Staff member, each tailored to specific operational needs.', '¿Todos en la casa necesitan acceso?', 'No. El acceso depende del rol de cada persona y de si realmente lo necesita.', 'No. El acceso depende del rol de la persona. Los roles son Propietario, Gerente y Personal, cada uno adaptado a necesidades operativas específicas.', array['access','users','accounts','family','roles']::text[]),
  ('FAQ-006', 'Staff & Permissions', 'Can staff use it without the homeowner?', 'Yes, if the appropriate permissions are provided.', 'Yes, if permission is provided. Staff can operate daily routines, manage task checklists, and update inventory independently based on assigned roles.', '¿El personal puede usarlo sin el propietario?', 'Sí, si se le otorgan los permisos correspondientes.', 'Sí, si se otorga el permiso. El personal puede realizar las rutinas diarias, manejar las listas de tareas y actualizar el Inventario de forma independiente según el rol asignado.', array['staff','autonomy','permissions','delegation','housekeeper']::text[]),
  ('FAQ-040', 'Staff & Permissions', 'What should staff check first?', 'Staff should open My Day, then read the Shift Handover.', 'Staff should start every shift by opening My Day for their assigned tasks, then reading Shift Handover for notes left by the previous shift or the manager.', '¿Qué debe revisar primero el personal?', 'Abra Mi Día y luego lea el Traspaso de Turno.', 'El personal debe comenzar cada turno abriendo Mi Día para ver sus tareas asignadas, y luego leyendo el Traspaso de Turno para ver las notas dejadas por el turno anterior o por el gerente.', array['staff workflow','my day','daily start','shift sequence']::text[]),
  ('FAQ-041', 'Staff & Permissions', 'What if I don''t know where something belongs?', 'Check Inventory location, Household Knowledge, or ask a supervisor.', 'Check Inventory location records first, search Household Knowledge next, and ask an appropriate supervisor only if still unlisted.', '¿Qué hago si no sé dónde va algo?', 'Revise la ubicación en Inventario, busque en Household Knowledge Base, o pregunte a un supervisor.', 'Primero revise los registros de ubicación en Inventario, luego busque en Household Knowledge Base (la base de conocimiento de la casa), y pregunte a un supervisor solo si el artículo sigue sin aparecer.', array['item placement','unknown location','lookup protocol']::text[]),
  ('FAQ-042', 'Staff & Permissions', 'Should staff create new inventory items?', 'Only if their assigned account permission role permits item creation.', 'Only if their account permissions allow it. Otherwise, missing items should be reported to managers via established channels.', '¿El personal debe crear artículos nuevos en el inventario?', 'Solo si el rol de su cuenta le permite crear artículos.', 'Solo si los permisos de su cuenta lo permiten. De lo contrario, informe los artículos faltantes al gerente por los canales establecidos.', array['staff creation','inventory privileges','adding items']::text[]),
  ('FAQ-043', 'Staff & Permissions', 'What if something is missing?', 'Record missing items immediately using established household workflows.', 'Record the item as depleted or missing according to the designated household reporting workflow.', '¿Qué hago si falta algo?', 'Registre de inmediato los artículos faltantes siguiendo el procedimiento de la casa.', 'Registre el artículo como agotado o faltante según el procedimiento de reporte establecido en la casa.', array['missing items','reporting shortage','out of stock log']::text[]),
  ('FAQ-044', 'Staff & Permissions', 'Why use the app instead of texting?', 'App information remains permanently organized, searchable, and central.', 'Because important instructions and requests stay permanently organized, central, and fully searchable instead of disappearing in chat history.', '¿Por qué usar la aplicación en lugar de mensajes de texto?', 'La información en la aplicación queda organizada, centralizada y se puede buscar.', 'Porque las instrucciones y solicitudes importantes quedan organizadas, centralizadas y se pueden buscar, en lugar de perderse en el historial de mensajes.', array['no text messages','central communication','searchable notes']::text[]),
  ('FAQ-045', 'Staff & Permissions', 'Who should have admin access?', 'Only trusted managers responsible for core home administration.', 'Only trusted individuals directly responsible for overall household information management (Homeowners, Lead Managers).', '¿Quién debe tener acceso de administrador?', 'Solo los gerentes de confianza responsables de la administración de la casa.', 'Solo las personas de confianza directamente responsables de administrar la información de la casa (propietarios y gerentes principales).', array['admin access','security','privileges','management']::text[]),
  ('FAQ-046', 'Staff & Permissions', 'Can permissions be changed?', 'Yes. Admins can update permission levels in account settings.', 'Yes. Permission profiles can be updated anytime inside administrative user management settings.', '¿Se pueden cambiar los permisos?', 'Sí. El administrador puede cambiar los niveles de permiso en Configuración.', 'Sí. Los perfiles de permisos se pueden actualizar en cualquier momento desde la administración de usuarios en Configuración.', array['update permissions','user access','role modification']::text[]),
  ('FAQ-047', 'Staff & Permissions', 'What should admins review regularly?', 'Audit active users, inventory quality, Needs Linking, and standards.', 'Admins should conduct periodic checks of active Users, Inventory quality, unresolved Needs Linking queues, and Household standards.', '¿Qué deben revisar los administradores con regularidad?', 'Los usuarios activos, la calidad del Inventario, la lista Needs Linking y los estándares de la casa.', 'Los administradores deben revisar periódicamente los usuarios activos, la calidad del Inventario, los artículos pendientes en Needs Linking y el cumplimiento de los estándares de la casa.', array['admin review','system audit','maintenance schedule']::text[]),
  ('FAQ-048', 'Troubleshooting', 'How do I maintain accuracy?', 'Execute small, consistent micro-updates rather than rare massive overhauls.', 'Create a routine of small, instant updates as changes occur instead of waiting for exhausting, periodic deep-clean overhauls.', '¿Cómo mantengo la información exacta?', 'Haga actualizaciones pequeñas y constantes en lugar de limpiezas grandes de vez en cuando.', 'Cree la rutina de hacer actualizaciones pequeñas en el momento en que ocurren los cambios, en lugar de esperar a una limpieza profunda que toma mucho tiempo.', array['accuracy','micro updates','data maintenance','consistency']::text[]),
  ('FAQ-050', 'Troubleshooting', 'I cannot see information.', 'Check account permissions, property selection dropdowns, and search filters.', 'Review assigned user Permissions, verify active Property selection, and check if active Search Filters are hiding entries.', 'No puedo ver la información.', 'Revise los permisos de su cuenta, la propiedad seleccionada y los filtros de búsqueda.', 'Revise los permisos asignados a su usuario, verifique cuál propiedad está seleccionada, y fíjese si algún filtro de búsqueda activo está ocultando los artículos.', array['missing data','visibility troubleshooting','permissions block','active filters']::text[]),
  ('FAQ-051', 'Troubleshooting', 'Search is not finding something.', 'Try broader terms, check category tags, or audit Needs Linking.', 'Try different keyword wording, search broader Category or Location lists, or check the Needs Linking queue for unlinked items.', 'La búsqueda no encuentra algo.', 'Use palabras más generales, revise las categorías, o consulte Needs Linking.', 'Pruebe con otras palabras, busque en listas más amplias de categoría o ubicación, o revise la lista Needs Linking por si el artículo quedó sin vincular.', array['search failure','find item','keyword mismatch']::text[]),
  ('FAQ-052', 'Troubleshooting', 'Something appears incorrect.', 'Confirm physical inventory reality and review historical activity logs.', 'Confirm current physical item reality, review historical changes in logs, and ensure edits were applied to the correct property.', 'Algo se ve incorrecto.', 'Verifique el inventario físico y revise el historial de cambios.', 'Verifique lo que hay físicamente, revise el historial de cambios, y confirme que las ediciones se hicieron en la propiedad correcta.', array['data error','wrong details','edit history']::text[]),
  ('FAQ-053', 'Staff & Permissions', 'Who do I contact for support?', 'Check the Help Center/FAQ first, then use your local organization protocol.', 'First check Help Center, FAQ, and Household Knowledge. If unresolved, use the support process established by your household admin.', '¿A quién contacto para obtener ayuda?', 'Primero revise el Centro de Ayuda, luego siga el procedimiento de su casa.', 'Primero revise el Centro de Ayuda y Household Knowledge Base. Si no se resuelve, siga el proceso de soporte establecido por el administrador de la casa.', array['support','help contact','technical support','troubleshooting escalation']::text[]),
  ('FAQ-056', 'Troubleshooting', 'What is Household Knowledge?', 'A repository storing operating instructions, guidelines, and home standards.', 'A dedicated digital repository storing operating manuals, homeowner preferences, vendor contacts, and explicit household operational standards.', '¿Qué es Household Knowledge Base?', 'Es donde se guardan las instrucciones, las guías y los estándares de la casa.', 'Es el archivo digital donde se guardan los manuales de uso, las preferencias del propietario, los contactos de proveedores y los estándares de trabajo de la casa.', array['household knowledge','home wiki','operating manual','standards']::text[]),
  ('FAQ-057', 'Troubleshooting', 'How do I record maintenance tasks?', 'Create recurring or one-time assignments inside the Tasks module.', 'Navigate to Tasks and select Add Task, setting desired recurrence intervals (e.g., quarterly filter changes) and assigned staff.', '¿Cómo registro las tareas de mantenimiento?', 'Cree tareas únicas o repetidas en el Centro de Tareas.', 'Vaya al Centro de Tareas y seleccione Agregar Tarea. Ahí puede definir cada cuánto se repite (por ejemplo, cambiar filtros cada tres meses) y a quién se le asigna.', array['maintenance','recurring tasks','home upkeep','repairs']::text[]),
  ('FAQ-058', 'Troubleshooting', 'Can I store preferred vendor contacts?', 'There''s a place for this, though it''s mostly empty today.', 'Vendor and service-provider contacts can be stored in Household Knowledge, but most households haven''t populated this yet — it''s built and ready to use, not pre-filled.', '¿Puedo guardar los contactos de proveedores?', 'Sí, hay un lugar para esto, aunque casi no tiene información todavía.', 'Los contactos de proveedores y de servicios se guardan en Household Knowledge Base. La sección ya está lista para usarse, pero todavía está casi vacía.', array['vendors','plumber','electrician','contacts','service directory']::text[]),
  ('FAQ-059', 'Troubleshooting', 'How do task recurrences work?', 'Tasks automatically regenerate on your chosen frequency schedule.', 'When marked complete, recurring tasks automatically calculate and schedule their next due date based on set daily, weekly, or monthly intervals.', '¿Cómo funcionan las tareas que se repiten?', 'La tarea se vuelve a crear sola según la frecuencia que usted eligió.', 'Cuando marca una tarea repetida como completada, el sistema calcula y programa automáticamente la siguiente fecha, según el intervalo diario, semanal o mensual configurado.', array['recurrence','repeating tasks','schedules','automated tasks']::text[]),
  ('FAQ-060', 'Troubleshooting', 'Can I attach manuals to household appliances?', 'Yes — save a link to the manufacturer''s manual in Household Knowledge.', 'Yes. A web link to an appliance''s manual or manufacturer page can be saved directly in its Household Knowledge record for quick staff reference.', '¿Puedo guardar los manuales de los electrodomésticos?', 'Sí. Guarde el enlace del manual del fabricante en Household Knowledge Base.', 'Sí. Puede guardar el enlace al manual o a la página del fabricante directamente en el registro del electrodoméstico en Household Knowledge Base, para consultarlo rápido.', array['appliance manuals','manual links','equipment guides']::text[]),
  ('FAQ-061', 'Troubleshooting', 'What are Household Standards?', 'Documented rules outlining exactly how tasks should be performed.', 'Clear, documented rules defining expectations for household execution, such as bed-making style, table setting, or laundry care.', '¿Qué son los estándares de la casa?', 'Son las reglas escritas que explican exactamente cómo se debe hacer cada tarea.', 'Son reglas claras y escritas que definen lo que se espera en la casa: cómo se tiende una cama, cómo se pone la mesa, o cómo se lava y cuida la ropa.', array['standards','expectations','execution rules','house rules']::text[]),
  ('FAQ-062', 'Staff & Permissions', 'Can I assign tasks to specific people?', 'Yes. Tasks can be delegated directly to assigned user accounts.', 'Yes. Individual tasks can be assigned directly to designated family members, managers, or staff profiles.', '¿Puedo asignar tareas a personas específicas?', 'Sí. Las tareas se pueden asignar directamente a una cuenta de usuario.', 'Sí. Las tareas individuales se pueden asignar directamente a familiares, gerentes o miembros del personal.', array['task assignment','delegation','assignee','staff chores']::text[]),
  ('FAQ-063', 'Troubleshooting', 'How do notifications work?', 'Notifications come through SMS and email, not push.', 'There''s no native push notification system. Real-time updates go out via opt-in SMS text alerts for urgent items, plus a weekly email digest covering upcoming needs, low stock, and pending items.', '¿Cómo funcionan las notificaciones?', 'Las notificaciones llegan por mensaje de texto y por correo, no como alertas de la aplicación.', 'No hay notificaciones automáticas dentro de la aplicación. Los avisos urgentes se envían por mensaje de texto (SMS) a quienes lo hayan autorizado, y una vez por semana se envía un resumen por correo con lo que viene, lo que está bajo de stock y lo que queda pendiente.', array['notifications','sms alerts','email digest','reminders']::text[]),
  ('FAQ-067', 'Staff & Permissions', 'What if I don''t know how the homeowner likes something done?', 'Check Household Knowledge before asking the homeowner.', 'Check Household Knowledge standards before asking. Most preferred execution methods are pre-documented.', '¿Qué hago si no sé cómo le gusta al propietario que se haga algo?', 'Revise Household Knowledge Base antes de preguntar.', 'Revise los estándares en Household Knowledge Base antes de preguntar. La mayoría de los métodos preferidos ya están documentados.', array['homeowner preference','household knowledge','staff protocol']::text[]),
  ('FAQ-068', 'Staff & Permissions', 'Why are household standards important?', 'They ensure everyone helping in the home follows uniform expectations.', 'Because they allow everyone helping in the home to follow the exact same expectations consistently without constant supervision.', '¿Por qué son importantes los estándares de la casa?', 'Aseguran que todos los que ayudan en la casa sigan las mismas expectativas.', 'Porque permiten que todas las personas que ayudan en la casa sigan exactamente las mismas expectativas, de forma constante y sin supervisión continua.', array['standards value','consistency','quality control','clear expectations']::text[]),
  ('FAQ-069', 'Staff & Permissions', 'What if I finish my assigned tasks early?', 'Review My Day for secondary priorities or general household needs.', 'Review My Day for remaining secondary priorities, pending maintenance, or general household preparation needs.', '¿Qué hago si termino mis tareas antes de tiempo?', 'Revise Mi Día para ver prioridades secundarias o necesidades generales de la casa.', 'Revise Mi Día para ver las prioridades secundarias pendientes, el mantenimiento pendiente o las necesidades generales de preparación de la casa.', array['finished early','extra tasks','my day','staff productivity']::text[]),
  ('FAQ-070', 'Staff & Permissions', 'What if I cannot complete a task?', 'Update task status or communicate the issue via app logs.', 'Update the task status with explanatory notes or communicate the issue directly through designated app workflows.', '¿Qué hago si no puedo terminar una tarea?', 'Actualice el estado de la tarea y explique el motivo en la aplicación.', 'Actualice el estado de la tarea agregando una nota que explique el motivo, o comunique el problema por los canales establecidos en la aplicación.', array['blocked task','incomplete work','task status note']::text[]),
  ('FAQ-071', 'Staff & Permissions', 'Can multiple staff members use the app?', 'Yes. Multiple staff users can log in under distinct individual profiles.', 'Yes. Multiple staff members can log into the app simultaneously with individual access accounts and designated roles.', '¿Pueden usar la aplicación varias personas del personal?', 'Sí. Cada persona entra con su propia cuenta individual.', 'Sí. Varias personas del personal pueden entrar a la aplicación al mismo tiempo, cada una con su propia cuenta y su rol asignado.', array['multi staff','team accounts','simultaneous access']::text[]),
  ('FAQ-072', 'Staff & Permissions', 'Can staff see everything in the home?', 'No. Staff only see areas permitted by their account role.', 'Only information allowed by their specific permission profiles is visible to staff accounts.', '¿El personal puede ver todo lo de la casa?', 'No. El personal solo ve lo que permite el rol de su cuenta.', 'Las cuentas del personal solo muestran la información permitida por su perfil de permisos.', array['privacy','restricted view','staff permissions']::text[]),
  ('FAQ-073', 'Staff & Permissions', 'What should staff update regularly?', 'Update moved items, used supplies, completed tasks, and relevant notes.', 'Important operational changes such as items moved, supplies used/depleted, tasks completed, and general household notes.', '¿Qué debe actualizar el personal con regularidad?', 'Los artículos movidos, los suministros usados, las tareas completadas y las notas importantes.', 'Los cambios importantes del día: artículos movidos de lugar, suministros usados o agotados, tareas completadas y notas generales de la casa.', array['staff updates','daily logging','real-time updates']::text[]),
  ('FAQ-074', 'Staff & Permissions', 'Why does the app help staff?', 'It replaces verbal memory demands with clear, searchable structure.', 'It replaces memory-based instructions and guesswork with clear, reliable, and easily searchable digital systems.', '¿En qué ayuda la aplicación al personal?', 'Reemplaza la memoria y las instrucciones verbales por una estructura clara que se puede buscar.', 'Reemplaza las instrucciones de memoria y las suposiciones por un sistema digital claro, confiable y fácil de consultar.', array['staff benefits','clarity','no guessing','less stress']::text[]),
  ('FAQ-075', 'Staff & Permissions', 'What if I have a suggestion for improving the household system?', 'Record it through designated household communication note logs.', 'Record it directly through the appropriate household note or feedback communication process in the app.', '¿Qué hago si tengo una sugerencia para mejorar el sistema de la casa?', 'Anótela en las notas de la casa dentro de la aplicación.', 'Regístrela directamente en las notas de la casa o por el canal de sugerencias establecido en la aplicación.', array['suggestions','feedback log','system improvement']::text[]),
  ('FAQ-086', 'Staff & Permissions', 'Who should manage the system?', 'Typically the homeowner or designated primary household manager.', 'Usually the primary homeowner or a designated professional house manager responsible for overall operational success.', '¿Quién debe administrar el sistema?', 'Normalmente el propietario o el gerente principal de la casa.', 'Por lo general, el propietario principal o un gerente profesional designado, responsable del funcionamiento general de la casa.', array['system manager','house manager','home administrator']::text[]),
  ('FAQ-087', 'Staff & Permissions', 'Who should have admin access?', 'Only trusted lead managers who control primary information structure.', 'Only trusted individuals directly responsible for structuring and managing core household digital records.', '¿Quién debe tener acceso de administrador?', 'Solo los gerentes principales de confianza que manejan la información central.', 'Solo las personas de confianza directamente responsables de organizar y administrar los registros digitales principales de la casa.', array['admin rights','system control','data security']::text[]),
  ('FAQ-088', 'Staff & Permissions', 'Can users have different permissions?', 'Yes. Access level is customized per individual user account.', 'Yes. Flexible permission structures ensure users see and edit only what is necessary for their assigned household role.', '¿Los usuarios pueden tener permisos diferentes?', 'Sí. El nivel de acceso se ajusta para cada cuenta.', 'Sí. Los permisos son flexibles, de modo que cada usuario solo ve y edita lo necesario para su rol en la casa.', array['user permissions','role access','custom visibility']::text[]),
  ('FAQ-089', 'Staff & Permissions', 'Why are permissions important?', 'They safeguard home data privacy and stop accidental information changes.', 'They protect sensitive household information and prevent accidental record deletions or unauthorized setting shifts.', '¿Por qué son importantes los permisos?', 'Protegen la privacidad de la casa y evitan cambios accidentales en la información.', 'Protegen la información delicada de la casa y evitan que se borren registros por accidente o que se cambien configuraciones sin autorización.', array['permission benefits','data security','prevent mistakes']::text[]),
  ('FAQ-090', 'Staff & Permissions', 'What should admins review regularly?', 'Users, inventory quality, Needs Linking, and household standards.', 'Users, general inventory quality, unlinked audit items, overall system accuracy, and household standards compliance.', '¿Qué deben revisar los administradores con regularidad?', 'Los usuarios, la calidad del Inventario, Needs Linking y los estándares de la casa.', 'Los usuarios, la calidad general del Inventario, los artículos sin vincular, la exactitud general del sistema y el cumplimiento de los estándares de la casa.', array['admin audit','regular maintenance','system check']::text[]),
  ('FAQ-091', 'Staff & Permissions', 'How do I keep information accurate?', 'Perform quick daily micro-updates instead of delaying until major cleanups.', 'Establish a habit of instant micro-updates as life happens instead of allowing data drift that requires major cleanup overhauls.', '¿Cómo mantengo la información exacta?', 'Haga actualizaciones pequeñas todos los días en lugar de esperar a una limpieza grande.', 'Cree el hábito de hacer actualizaciones pequeñas en el momento, en lugar de dejar que la información se desactualice y requiera una limpieza grande después.', array['data accuracy','micro habits','real time updates']::text[]),
  ('FAQ-092', 'Staff & Permissions', 'What happens when someone leaves the household team?', 'Promptly remove or adjust their account access permissions.', 'Immediately review user access management settings and deactivate or remove their assigned login permissions.', '¿Qué pasa cuando alguien deja el equipo de la casa?', 'Quite o ajuste de inmediato los permisos de su cuenta.', 'Revise de inmediato la administración de usuarios y desactive o elimine los permisos de acceso de esa persona.', array['offboarding','remove user','revoke access','staff departure']::text[]),
  ('FAQ-096', 'Troubleshooting', 'The app is not showing the information I expect. What should I check?', 'Check your login account, active property context, search filters, and permissions.', 'Check for correct account login, selected property context, active search filters, and profile view permissions.', 'La aplicación no muestra la información que espero. ¿Qué debo revisar?', 'Revise con qué cuenta entró, qué propiedad está seleccionada, los filtros de búsqueda y sus permisos.', 'Verifique que entró con la cuenta correcta, cuál propiedad está seleccionada, si hay filtros de búsqueda activos, y qué permisos de visualización tiene su perfil.', array['troubleshooting','missing information','filter check','property check']::text[]),
  ('FAQ-097', 'Troubleshooting', 'I cannot find an item. What should I do?', 'Try generic search terms, scan category views, or review Needs Linking.', 'Try broader alternate terms, search explicit category/location lists, or check the Needs Linking queue.', 'No encuentro un artículo. ¿Qué hago?', 'Use palabras más generales, revise las categorías, o consulte Needs Linking.', 'Pruebe con palabras alternativas más generales, busque en las listas de categoría o ubicación, o revise la lista Needs Linking.', array['item recovery','can''t find item','search tips']::text[]),
  ('FAQ-098', 'Troubleshooting', 'Something looks incorrect. Should I delete it?', 'Usually no. Review entry details first and edit to correct inaccuracies.', 'Usually no. Review details and historical edit logs first to determine and apply the proper update instead of deleting.', 'Algo se ve incorrecto. ¿Lo debo borrar?', 'Casi nunca. Primero revise los detalles y corrija lo que esté mal.', 'Casi nunca. Primero revise los detalles y el historial de cambios para entender qué pasó, y corrija el registro en lugar de borrarlo.', array['do not delete','data repair','edit error']::text[]),
  ('FAQ-099', 'Troubleshooting', 'What if I see duplicate information?', 'Confirm whether listings are true duplicates or separate location entries.', 'Verify whether items are genuine database duplicates or intentional separate listings for identical items stored in distinct physical locations.', '¿Qué hago si veo información duplicada?', 'Confirme si de verdad está duplicado o si son artículos iguales guardados en lugares distintos.', 'Verifique si se trata de un duplicado real, o si son registros separados a propósito para el mismo artículo guardado en ubicaciones físicas distintas (por ejemplo, jabón en cada baño).', array['duplicates','merged items','double entry']::text[]),
  ('FAQ-100', 'Troubleshooting', 'What is the best way to get help?', 'Check Help Center → FAQ → Household Knowledge → Escalate to support.', 'First check the in-app Help Center, master FAQ, and internal Household Knowledge. If unresolved, escalate through your designated support process.', '¿Cuál es la mejor manera de conseguir ayuda?', 'Revise el Centro de Ayuda, luego Household Knowledge Base, y si no se resuelve, avise a su supervisor.', 'Primero revise el Centro de Ayuda dentro de la aplicación y Household Knowledge Base. Si el problema sigue, escale por el proceso de soporte que se le indicó.', array['get help','support process','help sequence']::text[])
on conflict (id) do update set
  category = excluded.category,
  question = excluded.question,
  short_answer = excluded.short_answer,
  detailed_answer = excluded.detailed_answer,
  question_es = excluded.question_es,
  short_answer_es = excluded.short_answer_es,
  detailed_answer_es = excluded.detailed_answer_es,
  keywords = excluded.keywords;
